#!/bin/bash

#SBATCH --job-name=UseLocalPython
#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:01:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2022

# cd $HOME/pixelsplat/

source venv/bin/activate

srun python3 -u print_python_version.py
# srun python3 -uc "import torch; print('GPU available?', torch.cuda.is_available())"
