#!/bin/bash

#SBATCH --job-name=UseLocalPython
#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:15:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2022
module load CUDA/11.8.0
module load GCC/11.3.0
module load Python/3.10.4-GCCcore-11.3.0

python3 -m venv venvOld
source venvOld/bin/activate

srun python -u chunk_scenes.py
srun python -u generate_index.py
