#!/bin/bash

#SBATCH --job-name=UseLocalPython
#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:06:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2023
module load CUDA/12.1.1
module load GCC/12.3.0

# cd $HOME/pixelsplat/

source venvOld/bin/activate

pip install ninja
pip install wheel
pip install torch torchvision torchaudio
pip install -r requirements.txt
